In [80]:
import numpy as np

In [81]:
l1 = [12,13,43,53,56,35,32]
l2 = [23,67,54,89,34,37,56]

In [82]:
a = np.array(l1)
print(a)

[12 13 43 53 56 35 32]


In [83]:
a1 = np.array([1,2,3,4,5.,6,7,8], dtype = int)

In [84]:
a2 = np.array([11,22,33,44,55.,66,77,88], dtype = int)

In [85]:
np.random.rand(5)

array([0.47615071, 0.31433288, 0.6614815 , 0.01704228, 0.36404768])

In [86]:
np.random.randint(0,20,5)

array([ 0, 16, 14, 17, 12])

In [87]:
print(l1)

[12, 13, 43, 53, 56, 35, 32]


In [88]:
a1.shape

(8,)

In [89]:
a1.size

8

In [90]:
a1.ndim

1

In [91]:
a1.dtype

dtype('int64')

In [92]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [93]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
b1 = np.array([2,4,6,8,10])

In [95]:
b1 > 4

array([False, False,  True,  True,  True])

In [96]:
b1[b1 > 4]

array([ 6,  8, 10])

In [97]:
np.concatenate([a1,a2])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 22, 33, 44, 55, 66, 77, 88])

In [98]:
a1 = np.array([2, 4, 6, 8, 10, 12])
a2 = np.array([1, 3, 5, 7, 9, 11])

In [99]:
np.concatenate([a1, a2])

array([ 2,  4,  6,  8, 10, 12,  1,  3,  5,  7,  9, 11])

In [100]:
np.split(a1,2)

[array([2, 4, 6]), array([ 8, 10, 12])]

In [101]:
c1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [102]:
c2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [103]:
c1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [104]:
np.vsplit(c1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [105]:
np.hsplit(c1,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [107]:
np.stack([c1,c2])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [108]:
np.hstack([c1,c2])

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [109]:
np.vstack([c1,c2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
import pandas as pd

In [116]:
s1 = pd.Series(a1)

0     2
1     4
2     6
3     8
4    10
5    12
dtype: int64

In [122]:
c6 = np.array([1,2,3,4,5,6])

In [123]:
c7 = [1,2,3,4,5,6]

In [125]:
s2 = pd.Series(c7)

In [126]:
s2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64